# PyTorch Fundamentals

In [2]:
import torch
print(torch.__version__)

2.13.0+cu130


### Introduction to Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# matrix
matrix = torch.tensor([[7, 7], [7, 7]])
matrix

tensor([[7, 7],
        [7, 7]])

In [7]:
# tensor
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

### Random Tensors

In [8]:
# creating a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1954, 0.5442, 0.2865, 0.1642],
        [0.8024, 0.2757, 0.1462, 0.9206],
        [0.1576, 0.0823, 0.3822, 0.5544]])

In [10]:
# creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [18]:
# use torch.range
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**One of three problems in deep learning**
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# float 32 tensor
# the default is float32 even if you specify none
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # datatype is the tensor (float32, float16, etc..)
                               device = "None", # default is cpu, but can switch to cuda
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

**Getting information from tensors (tensor attributes)**

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [43]:
# creating a random tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4559, 0.5606, 0.4557, 0.0323],
        [0.0937, 0.5461, 0.4985, 0.8243],
        [0.8568, 0.5224, 0.3013, 0.8454]])

In [44]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4559, 0.5606, 0.4557, 0.0323],
        [0.0937, 0.5461, 0.4985, 0.8243],
        [0.8568, 0.5224, 0.3013, 0.8454]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
