# PyTorch Fundamentals

In [2]:
import torch
print(torch.__version__)

2.13.0+cu130


### Introduction to Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# matrix
matrix = torch.tensor([[7, 7], [7, 7]])
matrix

tensor([[7, 7],
        [7, 7]])

In [7]:
# tensor
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

### Random Tensors

In [8]:
# creating a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1954, 0.5442, 0.2865, 0.1642],
        [0.8024, 0.2757, 0.1462, 0.9206],
        [0.1576, 0.0823, 0.3822, 0.5544]])

In [10]:
# creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [11]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
# creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])