# PyTorch Fundamentals

In [3]:
import torch
print(torch.__version__)

2.13.0+cu130


### Introduction to Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# matrix
matrix = torch.tensor([[7, 7], [7, 7]])
matrix

tensor([[7, 7],
        [7, 7]])

In [7]:
# tensor
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

### Random Tensors

In [8]:
# creating a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1954, 0.5442, 0.2865, 0.1642],
        [0.8024, 0.2757, 0.1462, 0.9206],
        [0.1576, 0.0823, 0.3822, 0.5544]])

In [10]:
# creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# creating a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [18]:
# use torch.range
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**One of three problems in deep learning**
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# float 32 tensor
# the default is float32 even if you specify none
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # datatype is the tensor (float32, float16, etc..)
                               device = "None", # default is cpu, but can switch to cuda
                               requires_grad = False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

**Getting information from tensors (tensor attributes)**

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [43]:
# creating a random tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4559, 0.5606, 0.4557, 0.0323],
        [0.0937, 0.5461, 0.4985, 0.8243],
        [0.8568, 0.5224, 0.3013, 0.8454]])

In [44]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4559, 0.5606, 0.4557, 0.0323],
        [0.0937, 0.5461, 0.4985, 0.8243],
        [0.8568, 0.5224, 0.3013, 0.8454]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor opeartions)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# creating a tensor and adding 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [46]:
# multiplying tensor by 10
tensor * 10

tensor([10, 20, 30])

In [47]:
# subtracting tensor by 10
tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` wont' work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [48]:
# element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [49]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [60]:
# shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul
# torch.matmaul(tensor_A, tensor_B) # this results in an error
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [52]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

In [55]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [59]:
# the matrix multiplication operation works when tensor_B is trnasposed

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc. (tensor aggregation)

In [4]:
# creating a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean - note: torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [12]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))